=== danielfengyu/myjavaprojects/JAVA_HOMEWORK/dataloader/student.dtd
<?xml version='1.0' encoding="UTF-8"?>
<!ELEMENT age  (#PCDATA)>
<!ELEMENT email  (#PCDATA)>
<!ELEMENT gender   (#PCDATA)>
<!ELEMENT id  (#PCDATA)>
<!ELEMENT name  (#PCDATA)>
<!ELEMENT java  (#PCDATA)>
<!ELEMENT student (id,name,age,gender,email,java)>
<!ELEMENT students  (student+)>

=== danielfengyu/myjavaprojects/JAVA_HOMEWORK/dataloader/student.xml
<?xml version="1.0" encoding="gb2312"?>

<!-- <!DOCTYPE students PUBLIC "-//jiang guohai//students definition//EN" "student.dtd" > -->

<students xmlns="http://www.abc.com/ns/test" 
	  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xsi:schemaLocation="http://www.abc.com/ns/test student.xsd">


    <student>
        <id>200192001</id>
        <name>张三</name>
        <age>18</age>
        <gender>男</gender>
        <email>zs@abc.com</email>
        <java>98</java>
    </student>
	
    <student>
        <id>200192002</id>
        <name>王五</name>
        <age>25</age>
        <gender>男</gender>
        <email>ww@abc.com</email>
        <java>85</java>
    </student>

    <student>
        <id>200192003</id>
        <name>郑卫</name>
        <age>34</age>
        <gender>男</gender>
        <email>zw@abc.com</email>
        <java>75</java>
    </student>
	
    <student>
        <id>200192005</id>
        <name>张飞</name>
        <age>19</age>
        <gender>男</gender>
        <email>zf@abc.com</email>
        <java>58</java>
    </student>
	
    <student>
        <id>200192006</id>
        <name>李娜</name>
        <age>29</age>
        <gender>女</gender>
        <email>lina@abc.com</email>
        <java>99</java>
    </student>
	
    <student>
        <id>200192012</id>
        <name>赵云</name>
        <age>20</age>
        <gender>男</gender>
        <email>zy@abc.com</email>
        <java>100</java>
    </student>
	
    <student>
        <id>200192013</id>
        <name>周岚</name>
        <age>19</age>
        <gender>女</gender>
        <email>zll@abc.com</email>
        <java>55</java>
    </student>
	
    <student>
        <id>200192014</id>
        <name>周星星</name>
        <age>22</age>
        <gender>男</gender>
        <email>zxx@abc.com</email>
        <java>40</java>
    </student>
	
    <student>
        <id>200192015</id>
        <name>杨澜</name>
        <age>30</age>
        <gender>女</gender>
        <email>yl@abc.com</email>
        <java>78</java>
    </student>
	
    <student>
        <id>200192035</id>
        <name>朱凯</name>
        <age>22</age>
        <gender>男</gender>
        <email>dl_zk@abc.com</email>
        <java>69</java>
    </student>
    
    <student>
        <id>200192036</id>
        <name>艾东</name>
        <age>25</age>
        <gender>女</gender>
        <email>aidong@abc.com</email>
        <java>88</java>
    </student>
    
    <student>
        <id>200192044</id>
        <name>法拉利</name>
        <age>35</age>
        <gender>男</gender>
        <email>falali@163.com</email>
        <java>90</java>
    </student>
    
    <student>
        <id>200192045</id>
        <name>芙蓉</name>
        <age>21</age>
        <gender>女</gender>
        <email>furong@abc.com</email>
        <java>55</java>
    </student>
    
    
     <student>
        <id>200192064</id>
        <name>乌兰托娅</name>
        <age>21</age>
        <gender>女</gender>
        <email>wulan@163.com</email>
        <java>87</java>
    </student>
    
    <student>
        <id>200192066</id>
        <name>阿里木</name>
        <age>22</age>
        <gender>男</gender>
        <email>alimu@sina.com</email>
        <java>85</java>
    </student>
    
      <student>
        <id>200192067</id>
        <name>闰土</name>
        <age>32</age>
        <gender>男</gender>
        <email>runtu@sina.com</email>
        <java>83</java>
    </student>
 
    
</students>
